### ISSUE TITLE
Flutter build error

### ISSUE THREAD

**Issue by v0l** [dart-lang/logging#68]
Hi, 

Im running into a problem when i try to use this package, I have a flutter app project and a package in a sub-directory which references `logging: ^0.11.3+2`.

When running unit tests in the sub-project there is no issues but when trying to run the app it fails with the error listed below.

Should i add the logging package to my app? This doesn't seem correct to me..

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-PH)
    • Flutter version 1.9.1+hotfix.5 at C:\Users\kieran\Downloads\flutter_windows_v1.7.8+hotfix.3-stable\flutter
    • Framework revision 1aedbb1835 (12 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\kieran\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\kieran\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\kieran\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!
```

```
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Alogging%2Flogging.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:578:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:755:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:407:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
<asynchronous suspension>
#5      starter (package:frontend_server/server.dart:127:27)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/k/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by v0l** [comment]
Seems to be related to this: https://github.com/dart-lang/sdk/commit/d8462dd015f2dcd4397e0124c82ba1c934d3a569

Deleting the .packages file fixed this for me

**Comment by natebosch** [comment]
Closing since this is unrelated to the particular package in use.
